### ISSUE TITLE
Simulation directory not cleaned up properly

### ISSUE THREAD

**Issue by ojarvin** [TheSystemDevelopmentKit/rtl#16]
In the spice module (https://github.com/TheSystemDevelopmentKit/spice) when `preserve_iofiles = False` and `preserve_spicefiles = False`, the whole simulation directory is deleted. In my opinion this is desired behavior. The property `preserve_iofiles` probably works correctly here, but there should probably be the other property (equivalent to `preserve_spicefiles`), which defines whether everything else should be removed or not.

Right now the simulation directory is left with `work/` and some temporary files.

**Comment by mkosunen** [comment]
Closed by release v1.7
